spring:
  datasource:
    url: jdbc:mysql://129.204.68.95/myecercise?characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: huang
    password: 123456
  profiles:
    active: dev
  freemarker:
    suffix: .ftl
    content-type: text/html
    cache: false
    template-loader-path: classpath:/templates/
    charset: UTF-8
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
server:
  servlet:
    context-path: /myexercise

#开发环境
---
spring:
  profiles: dev
server:
  port: 8088


#正式环境
---
spring:
  profiles: pro
server:
  port: 80
