spring:
  datasource:
    url: jdbc:mysql://129.204.68.95/myecercise?characterEncoding=UTF-8&useAffectedRows=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: huang
    password: 123456
  profiles:
    active: dev
  freemarker:
    suffix: .ftl
    content-type: text/html
    cache: false
    template-loader-path: classpath:/templates/
    charset: UTF-8
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
  resources:
    static-locations: classpath:/static/,file:${upload-path}
  mvc:
    static-path-pattern: /**
    date-format: yyyy-MM-dd
server:
  servlet:
    context-path: /myexercise

#kaptcha验证码
kaptcha:
  height: 50
  width: 130
  content:
    length: 4
    source: abcdefghjklmnopqrstuvwxyz23456789
    space: 2
  font:
    color: black
    name: Arial
    size: 40
  background-color:
    from: lightGray
    to: white
  border:
    enabled: false
    color: black
    thickness: 1



#shiro配置

#开发环境
---
spring:
  profiles: dev
server:
  port: 8088
#mybatis:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#文件上传路径
upload-path: E:/test/


#正式环境
---
spring:
  profiles: pro
server:
  port: 80

#文件上传路径
upload-path: /usr/local/web/upload/


